name: ariokan_index
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  # Auth Signup feature deps (added T002)
  firebase_core: ^4.1.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  go_router: ^16.2.1
  get_it: ^8.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  alchemist: ^0.12.1
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  
flutter:
  uses-material-design: true
  generate: true
